url: https://foralienbureau.github.io
baseurl: /fundconst
title: Конструктор фандрайзинговых лендингов
description: >-
  Плагин для WordPress, с помощью которого можно создавать страницы для сбора пожертований.
lang: "ru-RU"
download_url: https://github.com/foralienbureau/fundconst/releases/download/v.0.0.2/fcon.zip
wiki_url: https://github.com/foralienbureau/fundconst/wiki
